### ISSUE TITLE
Cell height changes for wrong responses

### ISSUE THREAD

**Issue by dseaton** [open-craft/activetable-jsinput#4]
@smarnach @antoviaque The cell height changes after a wrong submission to active table. See my new example [p7 for Money Creation in Macro](https://github.com/open-craft/activetable-jsinput/blob/Daniel/Notes_and_Examples/p7_ActTable_MoneyCreation_LC2_HOA2.xml) 

[Studio Link](https://studio.edge.edx.org/container/i4x://DavidsonNext/Ann101/vertical/102bb8a023ce4d8bb0a7e1e4259faddf?action=new)

Here is a screenshot before any submission
![image](https://cloud.githubusercontent.com/assets/1703442/7951077/d9b1541a-0970-11e5-807b-aa51357a1d33.png)

Here is the screenshot after a blank submission (notice the scroll bar):
![image](https://cloud.githubusercontent.com/assets/1703442/7951080/fd0fd90e-0970-11e5-9b52-610815f38a6c.png)

**Comment by antoviaque** [comment]
@dseaton Thanks for the bug report! Is it good with you if we include the bugfixes in the next sprint, or do you have an urgent deadline on this? Usually changes/fixes are added to the next sprint, to preserve the current sprint commitments & workload, but I know you are dealing with tight deadlines at the moment, so I prefer to ask.

Same question about https://github.com/open-craft/jsinput-vectordraw/issues/18 (cc @mtyaka )

**Comment by dseaton** [comment]
@antoviaque Sorry for the delay. This active table issue is fine to be scheduled for next week.

**Comment by antoviaque** [comment]
@dseaton Sounds good - will do!

**Comment by dseaton** [comment]
Issue appears to be resolved.

[Studio Link](https://studio.edge.edx.org/container/i4x://DavidsonNext/Ann101/vertical/102bb8a023ce4d8bb0a7e1e4259faddf?action=new)

![screen shot 2015-06-09 at 4 25 29 pm](https://cloud.githubusercontent.com/assets/1703442/8068725/b3e3f910-0ec3-11e5-8772-b0984f874a7e.png)

**Comment by dseaton** [comment]
@antoviaque @Kelketek @smarnach Just applied the new code to a problem in Calculus. Was able to set the row and column heights individually where needed. So far, so good!

I'll be making more of these over the next few days, and willl keep you all posted. Thanks for you efforts!
